language: python

addons:
  postgresql: "9.4"

python:
  - "2.7"
  - "3.4"

env:
  - DJANGO="django==1.6.11"
  - DJANGO="django==1.8.2"

install:
  - pip install $DJANGO
  - pip install mock psycopg2
  - export PYTHONPATH=.

script:
  - python token/runtests/runtests.py
